# Generated by Django 2.2.12 on 2021-12-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0002_auto_20211202_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leave_Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type_of_leave', models.CharField(max_length=200)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Days', models.FloatField()),
                ('Daytype', models.CharField(max_length=200)),
                ('Session', models.CharField(max_length=200)),
                ('Reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameField(
            model_name='user_profile',
            old_name='designation',
            new_name='Designation',
        ),
    ]
