# Generated by Django 2.2.12 on 2021-12-06 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0003_auto_20211206_0338'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Apply_Leave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('LeaveType', models.CharField(max_length=200)),
                ('From', models.DateField()),
                ('To', models.DateField()),
                ('Days', models.FloatField()),
                ('Daytype', models.CharField(max_length=200)),
                ('Session', models.CharField(max_length=200)),
                ('Reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Leave_Registration',
        ),
        migrations.AddField(
            model_name='user_profile',
            name='Profile_pic',
            field=models.ImageField(default='SOME STRING', upload_to='images/'),
        ),
    ]
