# Generated by Django 2.2.12 on 2021-12-06 05:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmtapp', '0004_auto_20211206_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userapplyleave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leaveType', models.CharField(max_length=200)),
                ('fromdate', models.DateField()),
                ('to', models.DateField()),
                ('days', models.FloatField()),
                ('daytype', models.CharField(max_length=200)),
                ('session', models.CharField(max_length=200)),
                ('reason', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='User_Profile',
            new_name='UserProfile',
        ),
        migrations.DeleteModel(
            name='User_Apply_Leave',
        ),
    ]
