# Generated by Django 2.2.12 on 2021-12-06 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0006_auto_20211206_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Userrole',
            field=models.CharField(default='SOME STRING', max_length=200),
        ),
    ]
