# Generated by Django 2.2.12 on 2021-12-06 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0007_userprofile_userrole'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='Userrole',
        ),
    ]
