# Generated by Django 2.2.12 on 2021-12-07 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0009_auto_20211206_1144'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapplyleave',
            old_name='leaveType',
            new_name='leavetype',
        ),
    ]
