# Generated by Django 2.2.12 on 2021-12-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0011_auto_20211207_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplyleave',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
