# Generated by Django 2.2.12 on 2021-12-07 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0012_auto_20211207_0417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplyleave',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
