# Generated by Django 2.2.12 on 2021-12-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0013_auto_20211207_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplyleave',
            name='session',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
