# Generated by Django 2.2.12 on 2021-12-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0014_auto_20211207_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplyleave',
            name='session',
            field=models.CharField(default=False, max_length=200),
        ),
    ]
