# Generated by Django 2.2.12 on 2021-12-08 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0017_auto_20211208_0405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplyleave',
            name='session',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
