# Generated by Django 2.2.12 on 2021-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0019_auto_20211208_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='empid',
            field=models.IntegerField(default=0),
        ),
    ]
