# Generated by Django 2.2.12 on 2021-12-08 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0020_userprofile_empid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='empid',
        ),
    ]
