# Generated by Django 2.2.12 on 2021-12-08 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0023_auto_20211208_0712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userapplyleave',
            name='days',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='userapplyleave',
            name='daytype',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
