# Generated by Django 2.2.12 on 2021-12-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0025_auto_20211208_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapplyleave',
            name='fromdate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userapplyleave',
            name='to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
