# Generated by Django 2.2.12 on 2021-12-10 11:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmtapp', '0026_auto_20211210_0850'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminApplyLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adleavetype', models.CharField(max_length=200)),
                ('adfromdate', models.DateField(blank=True, null=True)),
                ('adto', models.DateField(blank=True, null=True)),
                ('addaytype', models.CharField(blank=True, max_length=200, null=True)),
                ('adsession', models.CharField(blank=True, max_length=200, null=True)),
                ('adreason', models.CharField(max_length=500)),
                ('aduser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
