# Generated by Django 2.2.12 on 2021-12-10 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pmtapp', '0027_adminapplyleave'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdminApplyLeave',
        ),
    ]
